/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NBackTop: typeof import('naive-ui')['NBackTop'];
    NButton: typeof import('naive-ui')['NButton'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NIcon: typeof import('naive-ui')['NIcon'];
  }
}
